import { useState } from "react";
import { Sidebar } from "./Sidebar";
import { Navbar } from "./Navbar";
import { LoansTable } from "./Table";

export default function LoanPortfolio() {
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);

  const loans = [
    {
      id: "L2833247",
      loanType: "Home Loan",
      borrower: "Vedika Sachar",
      borrowerAddress: "83 Yogi Ganj, Kadapa-516720",
      coBorrowerName: "Divit Vora",
      coBorrowerAddress: "24/543, Acharya Path Digvijay-052360",
      currentDPD: "81",
      sanctionAmount: "₹ 1934068",
      region: "West",
      status: "Under Process",
    },
    {
      id: "L2833243",
      loanType: "Car Loan",
      borrower: "Hrishita Agrawal",
      borrowerAddress: "86/622, Deo Path, Burhanpore 841186",
      coBorrowerName: "Mahika Tak",
      coBorrowerAddress: "58 Tata Road, Sultan Pur Gurgaon-010873",
      currentDPD: "100",
      sanctionAmount: "₹ 1842143",
      region: "North",
      status: "Monitoring",
    },
    {
      id: "L2833250",
      loanType: "Car Loan",
      borrower: "Priyansh Sonam",
      borrowerAddress: "H.No. 152 Andra Street Amritsar-417162",
      coBorrowerName: "Zaina Dara",
      coBorrowerAddress: "H.No. 42, Srivastava Marg, Junagadh-191124",
      currentDPD: "100",
      sanctionAmount: "₹ 4537889",
      region: "East",
      status: "Tracking",
    },
    {
      id: "L2833248",
      loanType: "Home Loan",
      borrower: "Priyansh Chanda",
      borrowerAddress: "24, Ray Chowk Gumasta-806332",
      coBorrowerName: "Zain Ghosh",
      coBorrowerAddress: "H.No. 56, Dagar Street Kolhapur-543860",
      currentDPD: "100",
      sanctionAmount: "₹ 2681712",
      region: "West",
      status: "Action Pending",
    },
    {
      id: "L2833260",
      loanType: "Home Loan",
      borrower: "Hrishita Sen",
      borrowerAddress: "94/38 Barad, Hubli-Dharwad-408790",
      coBorrowerName: "Shrey Kala",
      coBorrowerAddress: "63/68, Bhardwaj Street Bokaro 662204",
      currentDPD: "100",
      sanctionAmount: "₹ 4456808",
      region: "West",
      status: "Resolved",
    },
    {
      id: "L2833265",
      loanType: "Personal Loan",
      borrower: "Vivaan Virk",
      borrowerAddress: "H.No. 653 Dada Ganj Ichalkaranji 278923",
      coBorrowerName: "Elakshi Chahul",
      coBorrowerAddress: "16/45 Divan Road Jabalpur 982051",
      currentDPD: "76",
      sanctionAmount: "₹ 3863514",
      region: "West",
      status: "Monitoring",
    },
    {
      id: "L2833264",
      loanType: "Car Loan",
      borrower: "Nirvaan Mander",
      borrowerAddress: "543 Singhal Street, Bhilwara Jahangi Pur-348320",
      coBorrowerName: "Vikram Dutt",
      coBorrowerAddress: "H.No. 115, Saha Road Singrauli-049374",
      currentDPD: "90",
      sanctionAmount: "₹ 1256883",
      region: "South",
      status: "Keeping Track",
    },
    {
      id: "L2833266",
      loanType: "Personal Loan",
      borrower: "Nirvi Sahni",
      borrowerAddress: "41/42, Dua, Amroha-741190",
      coBorrowerName: "Dhanak Lalla",
      coBorrowerAddress: "48/41 Garde Path Ludhiana-709956",
      currentDPD: "75",
      sanctionAmount: "₹ 2687368",
      region: "East",
      status: "Work in Progress",
    },
    {
      id: "L2833267",
      loanType: "Personal Loan",
      borrower: "Samara Jain",
      borrowerAddress: "79/10 Barad Zila Tiruchirappalli 606938",
      coBorrowerName: "Chirag Tripathi",
      coBorrowerAddress: "23/11 Rawat Street, Panchkula-506035",
      currentDPD: "76",
      sanctionAmount: "₹ 3617146",
      region: "South",
      status: "Granted",
    },
    {
      id: "L2833268",
      loanType: "Personal Loan",
      borrower: "Aradhya Jayaraman",
      borrowerAddress: "410, Vohra Zila Moradabad 983541",
      coBorrowerName: "Shaan Hora",
      coBorrowerAddress: "35/41 Bajaj Nagar Nagaon-504713",
      currentDPD: "76",
      sanctionAmount: "₹ 1383439",
      region: "South",
      status: "Approved",
    },
    {
      id: "L2833269",
      loanType: "Home Loan",
      borrower: "Aditya Kumar",
      borrowerAddress: "15 Park Street, Chennai-600001",
      coBorrowerName: "Riya Kumar",
      coBorrowerAddress: "15 Park Street, Chennai-600001",
      currentDPD: "82",
      sanctionAmount: "₹ 2934068",
      region: "South",
      status: "Under Review",
    },
    {
      id: "L2833270",
      loanType: "Personal Loan",
      borrower: "Neha Singh",
      borrowerAddress: "45 MG Road, Bangalore-560001",
      coBorrowerName: "Raj Singh",
      coBorrowerAddress: "45 MG Road, Bangalore-560001",
      currentDPD: "95",
      sanctionAmount: "₹ 1534068",
      region: "South",
      status: "Pending",
    },
    {
      id: "L2833271",
      loanType: "Car Loan",
      borrower: "Rahul Sharma",
      borrowerAddress: "78 Civil Lines, Delhi-110054",
      coBorrowerName: "Priya Sharma",
      coBorrowerAddress: "78 Civil Lines, Delhi-110054",
      currentDPD: "88",
      sanctionAmount: "₹ 834068",
      region: "North",
      status: "In Process",
    },
    {
      id: "L2833272",
      loanType: "Home Loan",
      borrower: "Karan Malhotra",
      borrowerAddress: "22 Ring Road, Mumbai-400001",
      coBorrowerName: "Anita Malhotra",
      coBorrowerAddress: "22 Ring Road, Mumbai-400001",
      currentDPD: "79",
      sanctionAmount: "₹ 4934068",
      region: "West",
      status: "Under Process",
    },
    {
      id: "L2833273",
      loanType: "Personal Loan",
      borrower: "Sneha Patel",
      borrowerAddress: "33 Gandhi Road, Ahmedabad-380001",
      coBorrowerName: "Raj Patel",
      coBorrowerAddress: "33 Gandhi Road, Ahmedabad-380001",
      currentDPD: "85",
      sanctionAmount: "₹ 734068",
      region: "West",
      status: "Review",
    },
    {
      id: "L2833288",
      loanType: "Car Loan",
      borrower: "Vikram Seth",
      borrowerAddress: "91 Lake Road, Kolkata-700001",
      coBorrowerName: "Maya Seth",
      coBorrowerAddress: "91 Lake Road, Kolkata-700001",
      currentDPD: "92",
      sanctionAmount: "₹ 1834068",
      region: "East",
      status: "Monitoring",
    },
  ];

  return (
    <div className="flex h-screen bg-background">
      <Sidebar isOpen={isSidebarOpen} setIsOpen={setIsSidebarOpen} />
      <div className="flex-1 flex flex-col overflow-hidden">
        <Navbar onMenuClick={() => setIsSidebarOpen(!isSidebarOpen)} />
        <LoansTable loans={loans} />
      </div>
    </div>
  );
}
